### ISSUE TITLE
Can not compile on GNU/Linux 7.0 (wheezy) 

### ISSUE THREAD

**Issue by qermit** [sddm/sddm#19]
here is buildlog

```
[  4%] Automoc for target sddm
[  4%] Built target sddm_automoc
[  8%] Building CXX object src/CMakeFiles/sddm.dir/daemon/PowerManager.cpp.o
/home/kermit/devel/sddm/src/daemon/PowerManager.cpp:28:18: error: operator '!' has no right operand
/home/kermit/devel/sddm/src/daemon/PowerManager.cpp:40:28: error: operator '!' has no right operand
/home/kermit/devel/sddm/src/daemon/PowerManager.cpp:67:19: error: #elif with no expression
/home/kermit/devel/sddm/src/daemon/PowerManager.cpp:131:19: error: #elif with no expression
make[2]: *** [src/CMakeFiles/sddm.dir/daemon/PowerManager.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/sddm.dir/all] Error 2
make: *** [all] Error 2
```

here is source code:

``` C
#if !LOGIN1_FOUND
#include "Configuration.h"

#include <QProcess>
#endif
```

my gcc version:

gcc version 4.7.2 (Debian 4.7.2-5)
