### PR TITLE
Port to Qt6

### LINKED ISSUE #1251: Qt 6 will probably drop QProcess::setupChildProcess
See https://github.com/qt-creator/qt-creator/commit/6a66ced594ad0063b088bf743be7ff962bbb5616. I couldn't find any more information about that.

I assume this means it needs to be ported to plain `fork()` + `execve`.

### PR DESCRIPTION
**Pull request by davispuh**
Port to Qt 6. Main things:
* `RegExp` has been removed, instead use `QRegularExpression`
* No more `QProcess::setupChildProcess` but instead `setChildProcessModifier`
* `QSettings` now uses UTF-8
* `QStringRef` has been removed. There is [QStringView](https://doc.qt.io/qt-6/qstringview.html) but that looks useful only for UTF-16 and [QLatin1StringView](https://doc.qt.io/qt-6/qlatin1stringview.html) but we need local encoding/UTF-8 so not usable

Something changed regarding `QMetaType` so need to include `Auth*` stuff aswell otherwise got linking failures
```
[ 70%] Linking CXX executable sddm-helper
/usr/bin/ld: CMakeFiles/sddm-helper.dir/sddm-helper_autogen/mocs_compilation.cpp.o: in function `QtPrivate::MetaObjectForType<SDDM::Auth::Info, void>::metaObjectFunction(QtPrivate::QMetaTypeInterface const*)':
/usr/src/debug/sddm-git/build/src/helper/sddm-helper_autogen/mocs_compilation.cpp:924: undefined reference to `SDDM::Auth::staticMetaObject'
/usr/bin/ld: CMakeFiles/sddm-helper.dir/sddm-helper_autogen/mocs_compilation.cpp.o: in function `QtPrivate::MetaObjectForType<SDDM::Auth::Error, void>::metaObjectFunction(QtPrivate::QMetaTypeInterface const*)':
/usr/src/debug/sddm-git/build/src/helper/sddm-helper_autogen/mocs_compilation.cpp:924: undefined reference to `SDDM::Auth::staticMetaObject'
/usr/bin/ld: CMakeFiles/sddm-helper.dir/sddm-helper_autogen/mocs_compilation.cpp.o: in function `std::enable_if<QtPrivate::IsQEnumHelper<SDDM::Auth::Info>::Value, QDebug>::type operator<< <SDDM::Auth::Info>(QDebug, SDDM::Auth::Info)':
/usr/include/qt6/QtCore/qdebug.h:398: undefined reference to `SDDM::Auth::staticMetaObject'
/usr/bin/ld: CMakeFiles/sddm-helper.dir/sddm-helper_autogen/mocs_compilation.cpp.o: in function `std::enable_if<QtPrivate::IsQEnumHelper<SDDM::Auth::Error>::Value, QDebug>::typeoperator<< <SDDM::Auth::Error>(QDebug, SDDM::Auth::Error)':
/usr/include/qt6/QtCore/qdebug.h:398: undefined reference to `SDDM::Auth::staticMetaObject'
/usr/bin/ld: CMakeFiles/sddm-helper.dir/sddm-helper_autogen/mocs_compilation.cpp.o: in function `QMetaTypeIdQObject<SDDM::Auth::Info, 16>::qt_metatype_id()':
/usr/include/qt6/QtCore/qmetatype.h:1377: undefined reference to `SDDM::Auth::staticMetaObject'
/usr/bin/ld: CMakeFiles/sddm-helper.dir/sddm-helper_autogen/mocs_compilation.cpp.o:/usr/include/qt6/QtCore/qmetatype.h:1377: more undefined references to `SDDM::Auth::staticMetaObject' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/helper/CMakeFiles/sddm-helper.dir/build.make:280: src/helper/sddm-helper] Error 1
make[1]: *** [CMakeFiles/Makefile2:581: src/helper/CMakeFiles/sddm-helper.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Resolves #1251

### CODE REVIEW

**Review by Vogtinator — COMMENTED** [review]
IMO too early to merge this before at least a 0.20 release. For instance the Plasma theme will break if sddm-greeter doesn't use Qt 5.

Can you get this such that it works with Qt 5.15 as well as 6? Using the unversioned Qt targets in cmake and some `#ifdef` should be enough.

**Comment by davispuh** [comment]
I don't really need this to be merged. Just putting it out here for everyone. I didn't really test it much but I was able to login so there's that :sweat_smile: 

And yes it could be implemented in a way to support both Qt5 and Qt6 at same time but I'm not planning on investing any more time in this.

**Comment by cordlandwehr** [comment]
Hi @davispuh @Vogtinator , I wonder what the plan is to get Qt6 support into the master branch. Is there a plan to merge this PR? Or should it be adapted to a dual-build option for Qt5/Qt6?
I am really interested to get the main branch into a state that I can build it with Qt6 (to ease integration work on my Yocto setups) So I am open to work on what is missing.

**Comment by Vogtinator** [comment]
> Hi @davispuh @Vogtinator , I wonder what the plan is to get Qt6 support into the master branch. Is there a plan to merge this PR? Or should it be adapted to a dual-build option for Qt5/Qt6?

Yes. Going Qt 6 only is something for later IMO.

**Comment by Vogtinator** [comment]
Superseded by #1716
